[versions]
agp = "9.1.1"
moengageAndroidBom = "4.3.0"
glide = "5.0.9"
kotlin = "2.3.20"
googleServices = "4.4.4"
coreKtx = "1.17.0"
lifecycle = "2.9.4"
activityCompose = "1.10.1"
navigationCompose = "2.9.8"
composeBom = "2026.06.01"
materialIcons = "1.7.8"
firebaseBom = "34.4.0"
junit = "4.13.2"
timber = "5.0.1"
playServicesLocation = "21.3.0"
serializationJson = "1.9.0"
spotless = "7.0.4"
ktlint = "1.6.0"

[libraries]
glide = { module = " com.github.bumptech.glide:glide", version.ref = "glide" }
inapp = { module = "com.moengage:inapp" }
inbox-core = { module = "com.moengage:inbox-core" }
cards-core = { module = "com.moengage:cards-core" }
geofence = { module = "com.moengage:geofence" }
realtime-trigger = { module = "com.moengage:realtime-trigger" }
moengage-android-bom = { module = "com.moengage:android-bom", version.ref = "moengageAndroidBom" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcons" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

junit = { module = "junit:junit", version.ref = "junit" }
rich-notification = { module = "com.moengage:rich-notification" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
